[project]
name = "policyguard-ai"
version = "0.1.0"
description = "RAG-based organizational document assistant with RBAC"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "pydantic>=2.5.0",
    "pydantic-settings>=2.1.0",
    "openai>=1.3.0",
    "qdrant-client>=1.7.0",
    "pymupdf>=1.23.0",
    "python-docx>=1.1.0",
    "streamlit>=1.29.0",
    "pandas>=2.1.0",
    "python-dotenv>=1.0.0",
    "redis>=5.0.0",
    "prometheus-client>=0.19.0",
    "slowapi>=0.1.9",
    "python-jose[cryptography]>=3.3.0",
    "passlib[bcrypt]>=1.7.4",
    "python-multipart>=0.0.6",
    "sentence-transformers>=3.0.1"
]

[project.optional-dependencies]
dev = [
    # testing
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",

    # formatting / linting
    "black>=23.11.0",
    "ruff>=0.1.6",

    # type checking 
    "mypy>=1.7.0",

    # security 
    "bandit>=1.7.5",
    "pip-audit>=2.6.0",

    # pre-commit 
    "pre-commit>=3.6.0"
]

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["app*", "ui*", "scripts*"]
exclude = ["tests*", "data*"]


# PYTEST CONFIG
[tool.pytest.ini_options]
testpaths = ["app/tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --strict-markers --cov=app --cov-report=term-missing --cov-fail-under=10"


# BLACK CONFIG
[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  \.eggs
  | \.git
  | \.venv
  | venv
  | build
  | dist
)/
'''

# RUFF CONFIG 
[tool.ruff]
line-length = 100
target-version = "py311"
[tool.ruff.lint]
select = [
    "E", "F", "I",   # basic linting
    "B",             # bug risks
    "SIM",           # code simplification
    "UP",            # python upgrades
    "RET"            # return issues
]
ignore = ["B008"]


# MYPY
[tool.mypy]
ignore_missing_imports = true
exclude = [
    "redis_data/",
    "qdrant_storage/",
    "venv/",
    ".venv/",
]
python_version = "3.11"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
no_implicit_optional = true
disable_error_code = ["call-arg"]